{
 "title": "BID Splunk",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "VHDX",
    "query": "SHOW TAG VALUES FROM \"hyperv_storage\" WITH KEY = \"instance\""
   },
   {
    "name": "machine_cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"hyperv_processor\" WITH KEY = \"instance\" WHERE \"instance\" =~ /BIDAS[Vv]0(1[56]|3[12]|6[7]|7[1])/"
   },
   {
    "name": "machine_vhdx",
    "label": "VHDX",
    "query": "SHOW TAG VALUES FROM \"hyperv_storage\" WITH KEY = \"instance\" WHERE \"instance\" =~/BIDAS[Vv]0(1[56]|3[12]|6[7])/"
   },
   {
    "name": "machine_network",
    "label": "Network",
    "query": "SHOW TAG VALUES FROM \"hyperv_vmnet\" WITH KEY = \"instance\" WHERE \"instance\" =~ /^BIDAS[Vv]0(1[56]|3[12]|6[7]|7[2])/"
   },
   {
    "name": "machine_network_dc2",
    "label": "Network",
    "query": "SHOW TAG VALUES FROM \"hyperv_vmnet\" WITH KEY = \"instance\" WHERE \"instance\" =~ /^BIDAS[Vv]0(1[9]|20|3[34]|6[8]|7[1])/ "
   },
   {
    "name": "machine_vhdx_dc2",
    "label": "VHDX",
    "query": "SHOW TAG VALUES FROM \"hyperv_storage\" WITH KEY = \"instance\" WHERE \"instance\" =~ /BIDAS[Vv]0(1[9]|20|3[34]|6[8])/ "
   },
   {
    "name": "machine_cpu_dc2",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"hyperv_processor\" WITH KEY = \"instance\" WHERE \"instance\" =~ /BIDAS[Vv]0(1[9]|20|3[34]|6[8]|7[2])/ "
   },
   {
    "name": "machine_network_search_dc1",
    "label": "Network",
    "query": "SHOW TAG VALUES FROM \"hyperv_vmnet\" WITH KEY = \"instance\" WHERE \"instance\" =~ /^BIDAS[Vv]0(1[4]|2[4567])/ "
   },
   {
    "name": "machine_network_search_dc2",
    "label": "Network",
    "query": "SHOW TAG VALUES FROM \"hyperv_vmnet\" WITH KEY = \"instance\" WHERE \"instance\" =~ /^BIDAS[Vv]0(1[8]|2[8]|3[8])/ "
   },
   {
    "name": "machine_network_proxy_dc1",
    "label": "Network",
    "query": "SHOW TAG VALUES FROM \"hyperv_vmnet\" WITH KEY = \"instance\" WHERE \"instance\" =~ /^DC1CS3[Vv]00([12])/ "
   },
   {
    "name": "machine_network_proxy_dc2",
    "label": "Network",
    "query": "SHOW TAG VALUES FROM \"hyperv_vmnet\" WITH KEY = \"instance\" WHERE \"instance\" =~ /^DC2CS3[Vv]00([12])/ "
   },
   {
    "name": "sh_machine_vhdx",
    "label": "VHDX",
    "query": "SHOW TAG VALUES FROM \"hyperv_storage\" WITH KEY = \"instance\" WHERE \"instance\" =~/BIDAS[Vv]0(1[14]|2[456])/"
   },
   {
    "name": "sh_machine_vhdx_dc2",
    "label": "VHDX",
    "query": "SHOW TAG VALUES FROM \"hyperv_storage\" WITH KEY = \"instance\" WHERE \"instance\" =~/BIDAS[Vv]0(1[8]|2[8])/"
   }
  ]
 },
 "panels": [
  {
   "title": "DC1 IX Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC1 IX Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "instance",
         "operator": "=~",
         "value": "/BIDAS[Vv]0(1[56]|3[12]|6[7]|7[2])/"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC1 IX Read\\Write Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC1 IX Read\\Write Ops",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_instance reads/s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "query": "SELECT mean(\"Read_Operations_persec\") FROM \"hyperv_storage\" WHERE (\"instance\" =~ /$csv_volume/ AND \"instance\" =~ /^*BIDASv015*/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none) ",
       "select": [
        [
         { "params": [ "Read_Operations_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_vhdx$/" }
       ]
      },
      {
       "alias": "$tag_instance writes/s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Write_Operations_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_vhdx$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC1 IX Normalized IOPS (8KB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC1 IX Normalized IOPS (8KB)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "query": "SELECT mean(\"Read_Operations_persec\") FROM \"hyperv_storage\" WHERE (\"instance\" =~ /$csv_volume/ AND \"instance\" =~ /^*BIDASv015*/) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(none) ",
       "select": [
        [
         { "params": [ "Normalized_Throughput" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_vhdx$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC1 IX Network Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC1 IX Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance Bytes In",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_network$/" }
       ]
      },
      {
       "alias": "$tag_instance Bytes Out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_network$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC1 IX CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC1 IX CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_processor",
       "select": [
        [
         { "params": [ "Percent_Total_Run_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_cpu$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC1 Search Head Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Search Head  Disk Latency DC1",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/BIDAS[Vv]0(1[14]|2[456])/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC1 Search Head Network Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Search Heads DC1 VM Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance Bytes In",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "instance",
         "operator": "=~",
         "value": "/^$machine_network_search_dc1$/"
        }
       ]
      },
      {
       "alias": "$tag_instance Bytes Out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "instance",
         "operator": "=~",
         "value": "/^$machine_network_search_dc1$/"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC1 Forwarder Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forwarder Disk Latency DC1",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/BIDAS[Vv]0(1[2]|2[3])/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC2 IX Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC2 IX Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "instance",
         "operator": "=~",
         "value": "/BIDAS[Vv]0(1[9]|20|3[34]|6[8]|7[2])/"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC2 IX Read\\Write Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC2 IX Read\\Write Ops",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_instance Read",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Read_Operations_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_vhdx_dc2$/" }
       ]
      },
      {
       "alias": "$tag_instance Write",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Write_Operations_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_vhdx_dc2$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC2 IX Normalized IOPS (8KB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC2 IX Normalized IOPS (8KB)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Normalized_Throughput" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_vhdx_dc2$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC2 IX Network Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC2 IX Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance Bytes In",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_network_dc2$/" }
       ]
      },
      {
       "alias": "$tag_instance Bytes Out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_network_dc2$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC2 IX CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "DC2 IX CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_instance CPU",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_processor",
       "select": [
        [
         { "params": [ "Percent_Total_Run_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$machine_cpu_dc2$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC2 Search Head Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Search Head  Disk Latency DC2",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/BIDAS[Vv]0(1[8]|2[8])/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC2 Search Head Network Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Search Heads DC2 VM Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance Bytes In",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "instance",
         "operator": "=~",
         "value": "/^$machine_network_search_dc2$/"
        }
       ]
      },
      {
       "alias": "$tag_instance Bytes Out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "instance",
         "operator": "=~",
         "value": "/^$machine_network_search_dc2$/"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DC2 Forwarder Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forwarder Disk Latency DC2",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_storage",
       "select": [
        [
         { "params": [ "Latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/BIDAS[Vv]0(1[7]|3[5])/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "S3 DC1 Network Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Proxies DC1 - VM Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance Bytes In",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/DC1CS3[Vv]/" }
       ]
      },
      {
       "alias": "$tag_instance Bytes Out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/DC1CS3[Vv]/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "S3 DC2 Network Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Proxies DC2 - VM Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance Bytes In",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/DC2CS3[Vv]/" }
       ]
      },
      {
       "alias": "$tag_instance Bytes Out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "hyperv_vmnet",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/DC2CS3[Vv]/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}